The Activeeon team <contact@activeeon.com>
:toc: left
:numbered:
:source-highlighter: prettify
:sectlinks:
:linkattrs:
:sectanchors:
:icons: font
:stylesheet: ../../../styles/stylesheets/activeeon.css
:imagesdir: ../images
:description: ProActive Parallel Suite is an innovative Open Source solution (OW2) for acceleration and +
orchestration of applications, seamlessly integrated with the management of high-performance Clouds +
(Private and Public with bursting capabilities). +
ProActive platform features High-Performance Workflows and +
Application Parallelization, together with enterprise Scheduling and Orchestration coupled with the dynamic +
management of private Heterogeneous Grids and Clouds. +
With a ProActive platform, our users tackle at once the acceleration and orchestration of all demanding +
enterprise applications, and the management of their own Enterprise Cloud.
:keywords: proactive, activeeon, documentation, manual, help, doc
:docinfo1:

++++
<script>
var header = document.getElementById('header').innerHTML
var newHeader = header.replace("</h1>", "</h1><h4>Version " + conf.version + ' - ' + conf.date + "</h4>");
document.getElementById('header').innerHTML = newHeader
</script>
++++

++++
<script>
if(window.location.hostname.includes("doc.activeeon.com")){
    document.querySelectorAll('.studioUrl').forEach(function(element){
        element.href="https://try.activeeon.com/studio";
    });
    document.querySelectorAll('.schedulerUrl').forEach(function(element){
        element.href="https://try.activeeon.com/scheduler";
    });
    document.querySelectorAll('.rmUrl').forEach(function(element){
        element.href="https://try.activeeon.com/rm";
    });
    document.querySelectorAll('.automationDashboardUrl').forEach(function(element){
        element.href="https://try.activeeon.com/automation-dashboard/#/portal/cloud-automation";
    });
    document.querySelectorAll('.restUrl').forEach(function(element){
        element.href="https://try.activeeon.com/rest";
    });
    document.querySelectorAll('.catalogRestUrl').forEach(function(element){
        element.href="https://try.activeeon.com/catalog";
    });
    document.querySelectorAll('.catalogGraphQLUrl').forEach(function(element){
        element.href="https://try.activeeon.com/catalog/graphiql";
    });
}
</script>
++++
