The Activeeon team <contact@activeeon.com>
:toc: left
:toclevels: 1
:numbered:
:source-highlighter: highlightjs
:highlightjsdir: ../highlight
:highlightjs-theme: idea
:sectlinks:
:linkattrs:
:sectanchors:
:icons: font
:stylesheet: ../../../styles/stylesheets/activeeon.css
:imagesdir: ../images
:description: ProActive Parallel Suite is an innovative Open Source solution (OW2) for acceleration and +
orchestration of applications, seamlessly integrated with the management of high-performance Clouds +
(Private and Public with bursting capabilities). +
ProActive platform features High-Performance Workflows and +
Application Parallelization, together with enterprise Scheduling and Orchestration coupled with the dynamic +
management of private Heterogeneous Grids and Clouds. +
With a ProActive platform, our users tackle at once the acceleration and orchestration of all demanding +
enterprise applications, and the management of their own Enterprise Cloud.
:keywords: proactive, activeeon, documentation, manual, help, doc
:docinfo1:

++++
<script>
var header = document.getElementById('header').innerHTML
var newHeader = header.replace("</h1>", "</h1><h4>Version " + conf.version + ' - ' + conf.date + "</h4>");
document.getElementById('header').innerHTML = newHeader
</script>
++++
