[colophon]
[discrete]
== Legal notice

The Activeeon team (C) 2014 by Activeeon

****
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation; version 3 of the License.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
You should have received a copy of the GNU Affero General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
If needed, contact us to obtain a release under GPL Version 2 or 3 or a different license than the AGPL.
****

[dedication]
[discrete]
= Contributors and Contact information

[discrete]
== Team leader

====
*Denis Caromel*

INRIA 2004, Route des Lucioles, BP 93 +
06902 Sophia Antipolis Cedex, France +
phone: +33 492 387 631 +
fax: +33 492 387 971 +
e-mail: mailto:Denis.Caromel@inria.fr[Denis.Caromel@inria.fr]
====

[discrete]
== Activeeon company

        - Vladimir Bodnartchouk
        - Arnaud Contes
        - Cédric Dalmasso
        - Christian Delbé
        - Jean-Michel Guillaume
        - Clément Mathieu
        - Emil Salageanu
        - Jean-Luc Scheefer

[discrete]
== OASIS team

- Brian Amedro
- Francoise Baude
- Francesco Bongiovanni
- Sergei Dolgov
- Borelli Elvio
- Yu Feng
- Ludovic Henrio
- Fabrice Huet
- Virginie Legrand Contes
- Eric Madelaine
- Laurent Pellegrino
- Guilherme Peretti-Pezzi
- Franca Perrina
- Marcela Rivera
- Christian Ruz
- Bastien Sauvan
- Mathieu Schnoor
- Oleg Smirnov
- Marc Valdener
- Fabien Viale

[discrete]
== Former important contributors

-   Gaikwad Abhijeet (Option Pricing)
-   Germain Sigety (Scheduling)
-   Alexandre di Costanzo (P2P, B&B)
-   Julien Vayssiere (MOP, Active Objects)
-   Vincent Cave (Legacy Wrapping)
-   Laurent Baduel (Group Communications)
-   Matthieu Morel (Initial Component Work)
-   Romain Quilici
-   Mario Leyton (Skeleton)
