The following terms are used throughout the documentation:

[[_glossary_proactive_workflows_scheduling]]
ProActive Workflows & Scheduling::
The full distribution of ProActive for Workflows & Scheduling, it contains the <<_glossary_proactive_scheduler,*ProActive Scheduler*>>
 server, the
REST & Web interfaces, the command line tools. It is the commercial product name.

[[_glossary_proactive_scheduler]]
ProActive Scheduler::
Can refer to any of the following:
  * A complete set of ProActive components.
  * An archive that contains a released version of ProActive components, for example `activeeon_enterprise-pca_server-OS-ARCH-VERSION.zip`.
  * A set of server-side ProActive components installed and running on a <<_glossary_server_host,*Server Host*>>.

[[_glossary_resource_manager]]
Resource Manager:: ProActive component that manages <<_glossary_proactive_node,*ProActive Nodes*>> running on <<_glossary_compute_host,*Compute Hosts*>>.

[[_glossary_scheduler]]
Scheduler:: ProActive component that accepts <<_glossary_job,*Jobs*>> from users, orders the constituent <<_glossary_task,*Tasks*>> according to priority and resource availability, and eventually executes them on the resources (<<_glossary_proactive_node,*ProActive Nodes*>>) provided by the <<_glossary_resource_manager,*Resource Manager*>>.

NOTE: Please note the difference between *Scheduler* and <<_glossary_proactive_scheduler,*ProActive Scheduler*>>.

[[_glossary_rest_api]]
REST API:: ProActive component that provides RESTful API for the <<_glossary_resource_manager,*Resource Manager*>>, the <<_glossary_scheduler,*Scheduler*>> and the <<_glossary_catalog, *Catalog*>>.

[[_glossary_rm_web_interface]]
Resource Manager Web Interface:: ProActive component that provides a web interface to the <<_glossary_resource_manager,*Resource Manager*>>. Also called Resource Manager portal.

[[_glossary_scheduler_web_interface]]
Scheduler Web Interface:: ProActive component that provides a web interface to the <<_glossary_scheduler,*Scheduler*>>. Also called Scheduler portal.

[[_glossary_workflow_studio]]
Workflow Studio:: ProActive component that provides a web interface for designing <<_glossary_workflow,*Workflows*>>.

[[_glossary_automation_dashboard]]
Automation Dashboard:: Centralized interface for the following web portals: <<_glossary_workflow_automation_portal,*Workflow Execution*>>, <<_glossary_catalog_portal,*Catalog*>>, <<_glossary_analytics_portal,*Analytics*>>, <<_glossary_job_planner_portal,*Job Planner*>>, <<_glossary_service_automation_portal,*Service Automation*>>, <<_glossary_event_orchestration_portal,*Event Orchestration*>> and <<_glossary_notification_portal,*Notifications*>>.

[[_glossary_analytics]]
Analytics::  ProActive component responsible to gather monitoring information for <<_glossary_job,*Jobs*>> and <<_glossary_proactive_node,*ProActive Nodes*>>

[[_glossary_job_analytics]]
Job Analytics:: ProActive component, part of the <<_glossary_analytics,*Analytics*>> service, that provides an overview of executed workflows along with their input variables and results.

[[_glossary_job_gantt]]
Job Gantt:: ProActive component, part of the <<_glossary_analytics,*Analytics*>> service, that builds a _Gantt diagram_ of past <<_glossary_job,*Jobs*>> executions.

[[_glossary_node_gantt]]
Node Gantt:: ProActive component, part of the <<_glossary_analytics,*Analytics*>> service, that provides an overview of <<_glossary_proactive_node,*ProActive Nodes*>> usage over time.

[[_glossary_analytics_portal]]
Analytics portal:: Web interface of the <<_glossary_job_analytics,*Analytics*>> component.

[[_glossary_notification_service]]
Notification Service:: ProActive component that allows a user or a group of users to subscribe to different types of notifications (web, email, sms or a third-party notification) when certain event(s) occur (e.g., job In-Error state, job in Finished state, scheduler in Paused state, etc.).

[[_glossary_notification_portal]]
Notification portal:: Web interface to visualize notifications generated by the <<_glossary_notification_service,*Notification Service*>> and manage subscriptions.

[[_glossary_notification_subscription]]
Notification Subscription:: In <<_glossary_notification_service,*Notification Service*>>, a subscription is a _per-user_ configuration to receive notifications for a particular type of events.

[[_glossary_notification_third_party]]
Third Party Notification:: A <<_glossary_notification_methods,*Notification Method*>> which executes a script when the notification is triggered.

[[_glossary_notification_methods]]
Notification Method:: Element of a <<_glossary_notification_subscription,*Notification Subscription*>> which defines how a user is notified (portal, email, third-party, etc.).

[[_glossary_notification_channel]]
Notification Channel:: In the <<_glossary_notification_service,*Notification Service*>>, a channel is a notification container that can be notified and displays notifications to groups of users

[[_glossary_cloud_automation_service]]
Service Automation:: ProActive component that allows a user to easily manage any On-Demand Services (PaaS, IaaS and MaaS) with full Life-Cycle Management (create, deploy, pause, resume and terminate).

[[_glossary_service_automation_portal]]
Service Automation portal:: Web interface of the <<_glossary_cloud_automation_service,*Service Automation*>>.

[[_glossary_workflow_automation_portal]]
Workflow Execution portal:: Web interface, is the main portal of ProActive Workflows & Scheduling and the entry point for end-users to submit workflows manually, monitor their executions and access job outputs, results, services endpoints, etc.

[[_glossary_catalog]]
Catalog:: ProActive component that provides storage and versioning of <<_glossary_workflow,*Workflows*>> and other ProActive Objects. It is also possible to query the Catalog for specific <<_glossary_workflow,*Workflows*>> through a REST API and also with Graphql API.

[[_glossary_catalog_portal]]
Catalog portal:: Web interface of the <<_glossary_catalog,*Catalog*>> component.

[[_glossary_cloud_watch]]
Event Orchestration:: ProActive component that monitors a system, according to predefined set of rules, detects complex events and then triggers user-specified actions.

[[_glossary_event_orchestration_portal]]
Event Orchestration portal::Web interface of the <<_glossary_cloud_watch,*Event Orchestration*>> component.

[[_glossary_scheduling_api]]
Scheduling API:: ProActive component that offers a GraphQL endpoint for getting information about a ProActive Scheduler instance.

[[_glossary_connector_iaas]]
Connector IaaS:: ProActive component that enables to do CRUD operations on different infrastructures on public or private Cloud (AWS EC2, Openstack, VMWare, Kubernetes, etc).

[[_glossary_job_planner]]
Job Planner:: ProActive component providing advanced scheduling options for <<_glossary_workflow,*Workflows*>>.

[[_glossary_job_planner_portal]] 
Job Planner portal:: Web interface to manage the <<_glossary_job_planner,*Job Planner*>> service.

[[_glossary_workflow_bucket]]
Bucket:: ProActive notion used with the <<_glossary_catalog, *Catalog*>> to refer to a specific collection of ProActive Objects and in particular ProActive Workflows.

[[_glossary_server_host]]
Server Host::
  The machine on which <<_glossary_proactive_scheduler,*ProActive Scheduler*>> is installed.

`SCHEDULER_ADDRESS`::
  The IP address of the <<_glossary_server_host,*Server Host*>>.

[[_glossary_proactive_node]]
ProActive Node::
  One *ProActive Node* can execute one <<_glossary_task,*Task*>> at a time. This concept is often tied to the number of cores
  available on a <<_glossary_compute_host,*Compute Host*>>. We assume a task consumes one core (more is possible, see
  <<../user/ProActiveUserGuide.adoc#_multi_node_task,multi-nodes tasks>>), so on a 4 cores machines you might want to run 4 ProActive Nodes.
  One (by default) or more ProActive Nodes can be executed in a Java process on the <<_glossary_compute_host,*Compute Hosts*>> and
  will communicate with the <<_glossary_proactive_scheduler,*ProActive Scheduler*>> to execute tasks. We distinguish two types of **ProActive Nodes**:
- **Server** ProActive Nodes: Nodes that are running in the same host as ProActive server;
- **Remote** ProActive Nodes: Nodes that are running on machines other than ProActive Server.

[[_glossary_compute_host]]
Compute Host::
  Any machine which is meant to provide computational resources to be managed by the <<_glossary_proactive_scheduler,*ProActive Scheduler*>>. One or more <<_glossary_proactive_node,*ProActive Nodes*>> need to be running on the machine for it to be managed by the <<_glossary_proactive_scheduler,*ProActive Scheduler*>>.

[NOTE]
====
Examples of *Compute Hosts*:

* All machines of a cluster managed by <<_glossary_proactive_scheduler,*ProActive Scheduler*>>, except <<_glossary_server_host,*Server Host*>>.
* All desktop machines in an organisation that have <<_glossary_proactive_agent,*ProActive Agents*>> installed.
====

[[_glossary_node_source]]
Node Source::
  A set of <<_glossary_proactive_node,*ProActive Nodes*>> deployed using the same deployment mechanism and sharing the same access policy.

[[_glossary_node_source_infrastructure]]
Node Source Infrastructure::
  The configuration attached to a <<_glossary_node_source,*Node Source*>> which defines the deployment mechanism used to deploy <<_glossary_proactive_node,*ProActive Nodes*>>.

[[_glossary_node_source_policy]]
Node Source Policy::
  The configuration attached to a <<_glossary_node_source,*Node Source*>> which defines the <<_glossary_proactive_node,*ProActive Nodes*>> acquisition and access policies.

[[_glossary_scheduling_policy]]
Scheduling Policy::
  The policy used by the <<_glossary_proactive_scheduler,*ProActive Scheduler*>> to determine how <<_glossary_job,*Jobs*>> and <<_glossary_job,*Tasks*>> are scheduled.


`PROACTIVE_HOME`::
  The path to the extracted archive of <<_glossary_proactive_scheduler,*ProActive Scheduler*>> release, either on the <<_glossary_server_host,*Server Host*>> or on a <<_glossary_compute_host,*Compute Host*>>.

[[_glossary_workflow]]
Workflow::
  User-defined representation of a distributed computation. Consists of the definitions of one or more <<_glossary_task,*Tasks*>> and their dependencies.

[[_glossary_workflow_revision]]
Workflow Revision:: ProActive concept that reflects the changes made on a <<_glossary_workflow,*Workflow*>> during it development. Generally speaking, the term <<_glossary_workflow, *Workflow*>> is used to refer to the latest version of a <<_glossary_workflow_revision,*Workflow Revision*>>.

[[_glossary_generic_information]]
Generic Information:: Are additional information which are attached to <<_glossary_workflow,*Workflows*>> or <<_glossary_task,*Tasks*>>. See <<../user/ProActiveUserGuide.adoc#_generic_information,*generic information*>>.

[[_glossary_calendars_definition]]
Calendar Definition:: Is a json object attached by adding it to the <<_glossary_generic_information,*Generic Information*>>
of a <<_glossary_workflow,*Workflow*>>.

[[_glossary_job]]
Job::
  An instance of a <<_glossary_workflow,*Workflow*>> submitted to the <<_glossary_proactive_scheduler,*ProActive Scheduler*>>. Sometimes also used as a synonym for <<_glossary_workflow,*Workflow*>>.

[[_glossary_job_id]]
Job Id::
  An integer identifier which uniquely represents a Job inside the <<_glossary_proactive_scheduler,*ProActive Scheduler*>>.

[[_glossary_job_icon]]
Job Icon::
  An icon representing the Job and displayed in portals. The Job Icon is defined by the Generic Information *workflow.icon*.

[[_glossary_task]]
Task::
  A unit of computation handled by <<_glossary_proactive_scheduler,*ProActive Scheduler*>>. Both <<_glossary_workflow,*Workflows*>> and <<_glossary_job,*Jobs*>> are made of *Tasks*. A Task must define a <<_glossary_task_executable,*ProActive Task Executable*>> and can also define <<_glossary_additional_task_scripts, additional task scripts>>

[[_glossary_task_id]]
Task Id::
  An integer identifier which uniquely represents a Task inside a Job <<_glossary_proactive_scheduler,*ProActive Scheduler*>>. Task ids are only unique inside a given Job.

[[_glossary_task_executable]]
Task Executable::
  The main executable definition of a <<_glossary_task,*ProActive Task*>>. A Task Executable can either be a <<_glossary_task_executable_script,*Script Task*>>, a <<_glossary_task_executable_java,*Java Task*>> or a <<_glossary_task_executable_native,*Native Task*>>.

[[_glossary_task_executable_script]]
Script Task::
  A <<_glossary_task_executable,*Task Executable*>> defined as a script execution.

[[_glossary_task_executable_java]]
Java Task::
  A <<_glossary_task_executable,*Task Executable*>> defined as a Java class execution.

[[_glossary_task_executable_native]]
Native Task::
  A <<_glossary_task_executable,*Task Executable*>> defined as a native command execution.

[[_glossary_additional_task_scripts]]
Additional Task Scripts::
   A collection of scripts part of a <<_glossary_task,*ProActive Task*>> definition which can be used in complement to the main <<_glossary_task_executable,*Task Executable*>>. Additional Task scripts can either be <<_glossary_selection_script,*Selection Script*>>, <<_glossary_fork_environment_script,*Fork Environment Script*>>, <<_glossary_pre_script,*Pre Script*>>, <<_glossary_post_script,*Post Script*>>, <<_glossary_control_flow_script,*Control Flow Script*>> or <<_glossary_clean_script,*Cleaning Script*>>

[[_glossary_selection_script]]
Selection Script::
  A script part of a <<_glossary_task,*ProActive Task*>> definition and used to select a specific <<_glossary_proactive_node,*ProActive Node*>> to execute a ProActive Task.

[[_glossary_fork_environment_script]]
Fork Environment Script::
  A script part of a <<_glossary_task,*ProActive Task*>> definition and run on the <<_glossary_proactive_node,*ProActive Node*>> selected to execute the Task. Fork Environment script is used to configure the forked Java Virtual Machine process which executes the task.

[[_glossary_pre_script]]
Pre Script::
  A script part of a <<_glossary_task,*ProActive Task*>> definition and run inside the forked Java Virtual Machine, before the <<_glossary_task_executable,*Task Executable*>>.

[[_glossary_post_script]]
Post Script::
  A script part of a <<_glossary_task,*ProActive Task*>> definition and run inside the forked Java Virtual Machine, after the <<_glossary_task_executable,*Task Executable*>>.

[[_glossary_control_flow_script]]
Control Flow Script::
  A script part of a <<_glossary_task,*ProActive Task*>> definition and run inside the forked Java Virtual Machine, after the <<_glossary_task_executable,*Task Executable*>>, to determine control flow actions.

[[_glossary_control_flow_action]]
Control Flow Action::
  A dynamic workflow action performed after the execution of a <<_glossary_task,*ProActive Task*>>. Possible control flow actions are <<_glossary_control_flow_action_branch,*Branch*>>, <<_glossary_control_flow_action_loop,*Loop*>> or <<_glossary_control_flow_action_replicate,*Replicate*>>.

[[_glossary_control_flow_action_branch]]
Branch::
  A dynamic workflow action performed after the execution of a <<_glossary_task,*ProActive Task*>> similar to an IF/THEN/ELSE structure.

[[_glossary_control_flow_action_loop]]
Loop::
  A dynamic workflow action performed after the execution of a <<_glossary_task,*ProActive Task*>> similar to a FOR structure.

[[_glossary_control_flow_action_replicate]]
Replicate::
  A dynamic workflow action performed after the execution of a <<_glossary_task,*ProActive Task*>> similar to a PARALLEL FOR structure.

[[_glossary_clean_script]]
Cleaning Script::
  A script part of a <<_glossary_task,*ProActive Task*>> definition and run after the <<_glossary_task_executable,*Task Executable*>> and before releasing the <<_glossary_proactive_node,*ProActive Node*>> to the <<_glossary_resource_manager,*Resource Manager*>>.

[[_glossary_script_bindings]]
Script Bindings::
   Named objects which can be used inside a <<_glossary_task_executable_script,*Script Task*>> or inside <<_glossary_additional_task_scripts,*Additional Task Scripts*>> and which are automatically defined by the <<_glossary_proactive_scheduler,*ProActive Scheduler*>>. The type of each script binding depends on the script language used.

[[_glossary_task_icon]]
Task Icon::
  An icon representing the Task and displayed in the Studio portal. The Task Icon is defined by the Task Generic Information *task.icon*.

[[_glossary_proactive_agent]]
ProActive Agent::
  A daemon installed on a <<_glossary_compute_host,*Compute Host*>> that starts and stops <<_glossary_proactive_node,*ProActive Nodes*>> according to a schedule, restarts <<_glossary_proactive_node,*ProActive Nodes*>> in case of failure and enforces resource limits for the <<_glossary_task,*Tasks*>>.