= Install

Execute a normal build with gradle:

----
./gradlew clean build
----

Upon success open `index.html` to check your changes.

----
firefox build/asciidoc/html5/index.html
----

Do not forget to follow the naming and capitalization guidelines at the end of this README.

= Asciidoctor

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

http://asciidoctor.org/docs/user-manual/

To write  documentation with live preview see http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/

Simplified installation procedure:

----
gem install bundler
bundle install
mkdir -p build
bundle exec guard
----

= How to write ProActive's documentation

* Please read the glossary and use the terms defined in it.
* User interface labels, buttons and actions should be written in _italic_
    ** For instance, "Click on _Submit_ in the web portal"

* Use capitals for ProActive's terms, as defined in the glossary
    ** Workflow, Job, Scheduler

* Use capitals for acronyms: SSH, URL,...

* Lines should 120 characters wide max

* Write code with blocks (----)
+
----
blahblahbcode
----

* If you need to create diagrams: please use https://docs.google.com/a/activeeon.com/document/d/1_krRw8h7i_F1CqfV7H--WHMPPI2nA1wfHsw_x6QIWpc/edit?usp=sharing
 ** Mind the "ProActive" colors #E87224 and #1c3067
