
In addition to variables, another key/value structure can be accessed inside a script: *_Generic Information_*.

Generic information semantics differ from <<_job_variables>> semantics in the following way:

* Generic information can be accessed inside a script, but cannot be modified.
* Generic information can be defined at *job level* or at *task level*. If the same generic information is defined at job level and at task level, the latter value takes precedence inside the task scope.
* Generic information cannot be used directly inside the workflow with the syntax ${} (See  <<_job_variables>>).
* Generic information are used in general internally by the scheduler, for example to provide information to the scheduling loop on how to handle the task. An example of such generic information is the _START_AT_ info used inside <<_cron_tasks>>.
* Generic information can use in their definition job/task variables patterns, pattern replacements can be done at execution time when using task generic information.

Example of a generic information definition:

For example:
[source, xml]
----
<task ... >
    <genericInformation>
        <info name="ginfo" value="${test}"/>
    </genericInformation>
    ...
</task>
----

=====  Icon management variables

There are specific variables that are dedicated to icon management.
The icon of a workflow is specified inside Workflow Generic Information using the keyword `workflow.icon`.
The icon of a task is specified inside Task Generic Information using the keyword `task.icon`.

These generic information are used in ProActive portals for proper visualization of workflow and task icons