
=== Introduction
The <<_glossary_job_planner,*Job Planner*>> schedules <<_glossary_workflow,*Workflows*>>.
 A <<_glossary_workflow,*Workflow*>> is scheduled by the <<_glossary_job_planner,*Job Planner*>> if
  an <<_glossary_execution_calendars_object,*Execution Calendars Object*>> is attached to the
   <<_glossary_generic_information,*Generic Information*>> of a <<_glossary_workflow,*Workflow*>>.

=== Execution Calendars Object Syntax
Below is an example of an <<_glossary_execution_calendars_object,*Execution Calendars Object*>>. It has a cron
expression attached as "cron" and a name as "name".
The name must be unique and submission will be rejected if a name clashes with an already existing
<<_glossary_execution_calendars_object,*Execution Calendars Object*>> inside the <<_glossary_job_planner,*Job Planner*>>.
----
EXECUTION_CALENDARS =
{
    "name": "weekdaysEveryHourAt23MinutsPast",
    "cron": "0 23 0 ? * MON,TUE,WED,THU,FRI *"
}
----
One can see the cron expression "0 23 0 ? * MON,TUE,WED,THU,FRI *", which follows the quartz cron expression syntax explained in the
<<_job_planner_cron_expression_syntax, Quartz Cron Expression Syntax>> section. The cron expression in this example
 executes 23 minutes past every hour, on working days (Monday to Friday).

==== Inclusion Calendar

The purpose of the inclusion calendar is to use ICS file to launch workflows during events. For each events a pre-defined action will be executed an will define when the workflow will be executed.

===== Available inclusion actions
 - EXECUTE_AT_START
 - POSTPONE_TO_NEXT_WORKING_DAY

===== Generic Information example : 
EXECUTION_CALENDAR = { "inclusion_calendars":[{  "calendar": {"url": "http://localhost:8080/myCalendars/myInclusionCalendar.ics"}, "rule": { "action": "EXECTURE_At_START" }]}

==== Exclusion Calendar

===== External calendar retrieved from URL

If an exclusion calendar is not retrievable it is blocking the <<_glossary_workflow,*Workflow*>> submission.
An exclusion calendar can become not retrievable if it cannot be downloaded from its URL and the
<<_glossary_job_planner,*Job Planner*>> cache doesn't hold a copy.

==== Troubleshooting in ProActive Studio
The name of the <<_glossary_execution_calendars_object,*Execution Calendars Object*>> must be unique.
The Studio displays "Unknown Error", if anything in the <<_glossary_execution_calendars_object,*Execution Calendars Object*>>
is not correctly formatted or the name clashes with existing <<_glossary_execution_calendars_object,*Execution Calendars Objects*>>.

Please validate the <<_glossary_execution_calendars_object,*Execution Calendars Object*>> beforehand
http://jsonlint.com/[with websites like this.]

Be aware that the "Unknown Error" is also displayed, when the <<_glossary_execution_calendars_object,*Execution Calendars Object*>>
name clashes with existing <<_glossary_execution_calendars_object,*Execution Calendars Objects*>>.
You can list existing <<_glossary_execution_calendars_object,*Execution Calendars Objects*>> with the
<<_glossary_job_planner,*Job Planner*>> REST API.


=== Job Planner Submission
When you are using the <<_glossary_workflow_studio,*Workflow Studio*>>, add an
<<_glossary_execution_calendars_object,*Execution Calendars Object*>> to <<_glossary_generic_information,*Generic Information*>>
of a <<_glossary_workflow,*Workflow*>> and click execute.
 The <<_glossary_workflow_studio,*Workflow Studio*>> automatically detect the
 <<_glossary_execution_calendars_object,*Execution Calendars Object*>> and submits the <<_glossary_workflow,*Workflow*>>
 accoordingly.

If you manually submit <<_glossary_workflow,*Workflows*>> intended for the
<<_glossary_job_planner,*Job Planner*>> , you need to submit it to its REST API.

The proactive-client does currently not support <<_glossary_job_planner,*Job Planner*>>
 <<_glossary_workflow,*Workflows*>>.


[[_job_planner_cron_expression_syntax]]
==== Quartz Cron Expression Syntax
The cron expression syntax follows the quarts-cron syntax.
 Please refer to the  http://www.quartz-scheduler.org/documentation/quartz-2.x/tutorials/crontrigger.html#format[quartz format documentation] for further details.

http://www.cronmaker.com/[You can generate your quartz cron expression here.]

