*ProActive Scheduler* supports the following nodes topologies for *multi-nodes tasks*.

* *Arbitrary* topology does not imply any restrictions on nodes location

[source,xml]
----
<parallel numberOfNodes="4">
    <topology>
        <arbitrary/>
    </topology>
</parallel>
----

* *Best proximity* - the set of closest nodes among those which are not executing other tasks.

[source,xml]
----
<parallel numberOfNodes="4">
    <topology>
        <bestProximity/>
    </topology>
</parallel>
----

* *Threshold proximity* - the set of nodes within a threshold proximity (in microseconds).

[source,xml]
----
<parallel numberOfNodes="4">
    <topology>
        <thresholdProximity threshold="100"/>
    </topology>
</parallel>
----

* *Single Host* - the set of nodes on a single host.

[source,xml]
----
<parallel numberOfNodes="4">
    <topology>
        <singleHost/>
    </topology>
</parallel>
----

* *Single Host Exclusive* - the set of nodes of a single host exclusively. The host with selected nodes will be reserved for the user.

[source,xml]
----
<parallel numberOfNodes="4">
    <topology>
        <singleHostExclusive/>
    </topology>
</parallel>
----

For this task the scheduler will try to find a host with 4 nodes. If there is no such a host another one will be used with a bigger capacity (if exists). In this case extra nodes on this host will be also occupied by the task but will not be used for the execution.

* *Multiple Hosts Exclusive* - the set of nodes filled in multiple hosts. Hosts with selected nodes will be reserved for the user.

[source,xml]
----
<parallel numberOfNodes="4">
    <topology>
        <multipleHostsExclusive/>
    </topology>
</parallel>
----

For this task the scheduler will try to find 4 nodes on a set of hosts. If there is no such a set which gives you exactly 4 nodes another one will be used with a bigger capacity (if exists). In this case extra nodes on this host will be also occupied by the task but will not be used for the execution.

* *Different Hosts Exclusive* - the set of nodes each from a different host. All hosts with selected nodes will be reserved for the user.

[source,xml]
----
<parallel numberOfNodes="4">
    <topology>
        <differentHostsExclusive/>
    </topology>
</parallel>
----

For this task the scheduler will try to find 4 hosts with one node on each. If number of "single node" hosts are not enough hosts with bigger capacity will be selected. In this case extra nodes on this host will be also occupied by the task but will not be used for the execution.
