To install a ProActive package, you can use the ProActive CLI by providing a path to your package.
It can be a local directory, a ZIP file or can be a URL to a web directory, a direct-download ZIP file, a GitHub repository or ZIP or a directory inside a GitHub repository.
Please note that URL forwarding is supported.

====== In non-interactive mode

* To install a package located in a local directory or ZIP

[source]
----
$ PROACTIVE_HOME/bin/proactive-client -pkg /Path/To/Local/Package/Directory/Or/Zip
----

* To install a package located in a web folder (Supports only Apache Tomcat directory listing)

[source]
----
$ PROACTIVE_HOME/bin/proactive-client -pkg http://example.com/installablePackageDirectory/
----

* To install a package with a direct download ZIP URL:

[source]
----
$ PROACTIVE_HOME/bin/proactive-client -pkg https://s3.eu-west-2.amazonaws.com/activeeon-public/proactive-packages/package-example.zip
----

* To install a package located in a GitHub repository (either in the repository root or in a sub-folder within a repository):

[source]
----
$ PROACTIVE_HOME/bin/proactive-client -pkg https://github.com/ow2-proactive/hub-packages/tree/master/package-example
----

====== In interactive mode

* To install a package located in any of the aforementioned possible locations

[source]
----
$ PROACTIVE_HOME/bin/proactive-client
> installpackage(PackagePathOrURL)
----
