
NOTE: New Node Source policies can be dynamically plugged into the Resource Manager. In order to do that, it is required to add classes extending the link:../javadoc/org/ow2/proactive/resourcemanager/nodesource/policy/NodeSourcePolicy.html[NodeSourcePolicy class] in the server class path and update the policy implementation list in the configuration file (+PROACTIVE_HOME/config/rm/nodesource/policies+).

==== Static Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.StaticPolicy`

*Static node source policy* starts node acquisition when nodes are added
to the node source and never removes them. Nevertheless, nodes can be
removed by user request. To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

==== Restart Down Node Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.RestartDownNodePolicy`

*Restart down node policy* automatically redeploy nodes when they are disconnected from the Resource Manager (for example after a network failure or a machine reboot).
To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *checkNodeStateEach* - interval in milliseconds used to check nodes availability. For example, if this interval is set to 30 minutes the policy will redeploy nodes after a disconnection of 30 minutes.

==== Time Slot Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.TimeSlotPolicy`

*Time slot policy* is aimed to acquire nodes for a specific time window with an
ability to do it periodically. To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *acquireTime* - Absolute acquire date (e.g. "6/3/10 1:18:45 PM
    CEST").

-   *releaseTime* - Absolute releasing date (e.g. "6/3/10 2:18:45 PM
    CEST").

-   *period* - Period time in millisecond (default is 86400000).

-   *preemptive* - Preemptive parameter indicates the way of releasing
    nodes. If it is true, nodes will be released without waiting the end
    of jobs running on (default is false).

==== Cron Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.CronPolicy`

*Cron policy* is aimed to acquire and remove nodes at a specific time
defined in the cron syntax. To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *nodeAcquision* - The time policy will trigger the deployment of
    all nodes (e.g. "0 12 \* \* \*" every day at 12.00).

-   *nodeRemoval* - The time policy will trigger the removal of all
    nodes (e.g. "0 13 \* \* \*" every day at 13.00).

-   *preemptive* - Preemptive parameter indicates the way of releasing
    nodes. If it is true, nodes will be released without waiting the end
    of jobs running on (default is false).

-   *forceDeployment* - If for the example above (the deployment
    starts every day at 12.00 and the removal starts at 13.00) you are
    creating the node source at 12.30 the next deployment will take
    place the next day. If you'd like to force the immediate deployment
    set this parameter to true.

==== Release Resources When Scheduler Is Idle

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.ReleaseResourcesWhenSchedulerIdle`

*"Release resources when scheduler is idle" policy* removes all nodes from
the infrastructure when the scheduler is idle and acquires them when a
new job is submitted. This policy may be useful if there is no need to
keep nodes alive permanently. Nodes will be released after a specified
"idle time". This policy will use a listener of the scheduler, that is
why its URL, its user name and its password have to be specified.
To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *schedulerURL* - URL of the Scheduler, e.g. pnp://mymachine:64738, pamr://0, etc

-   *schedulerCredentialsPath* - Path to the credentials used for
    scheduler authentication.

-   *schedulerAwarePolicyNodeSourceRecoveryDelay* - Delay in ms for the Resource Manager to recover a broken node source using the ReleaseResourcesWhenSchedulerIdle policy.

-   *schedulerAwarePolicyNodeSourceRecoveryTrialsNumber* - Number of attempts for the Resource Manager to recover to recover a broken node source using the ReleaseResourcesWhenSchedulerIdle policy.

-   *idleTime* - Idle time in millisecond to wait before removing all
    nodes (default is 60000).


==== Scheduler Loading Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.SchedulerLoadingPolicy`

*Scheduler loading policy* acquires/releases nodes according to the
scheduler loading factor. This policy allows to configure the number of
resources which will be always enough for the scheduler. Nodes are
acquired and released according to scheduler loading factor which is a
number of tasks per node.

It is important to correctly configure maximum and minimum nodes that this
policy will try to hold. Maximum number should not be greater than
potential nodes number which is possible to deploy to underlying
infrastructure. If there are more currently acquired nodes than
necessary, policy will release them one by one after having waited for a
"release period" delay. This smooth release procedure is implemented
because deployment time is greater than the release one. Thus, this
waiting time deters policy from spending all its time trying to deploy
nodes.

To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *schedulerURL* - URL of the Scheduler, e.g. pnp://mymachine:64738, pamr://0, etc

-   *schedulerCredentialsPath* - Path to the credentials used for
    scheduler authentication.

-   *schedulerAwarePolicyNodeSourceRecoveryDelay* - Delay in ms for the Resource Manager to recover a broken node source using the SchedulerLoadingPolicy.

-   *schedulerAwarePolicyNodeSourceRecoveryTrialsNumber* - Number of attempts for the Resource Manager to recover to recover a broken node source using the SchedulerLoadingPolicy.

-   *refreshTime* - Time between each calculation of the number of needed
nodes.

-   *minNodes* - Minimum number of nodes to deploy

-   *maxNodes* - Maximum number of nodes to deploy

-   *loadFactor* - Number of tasks per node. Actually, if this number is
*N*, it does not means that there will be exactly *N* tasks executed on
each node. This factor is just used to compute the total number of
nodes. For instance, let us assume that this factor is 3 and that we
schedule 100 tasks. In that case, we will have 34 (= upper bound of
100/3) started nodes. Once one task finished and the refresh time
passed, one node will be removed since 99 divided by 3 is 33. When there
will remain 96 tasks (assuming that no other tasks are scheduled
meanwhile), an other node will be removed at the next calculation time,
and so on and so forth...

-   *refreshCycleWindow* - Number of refresh cycles used to memorize scheduler load. Actual load will be computed as an average.

-   *releaseDelay* - Delay in milliseconds used before removing a free node. This parameter can be used for paid cloud instances such as Amazon, Azure, etc. when their policy define a minimum granularity on instance costs. Example for Amazon : 3600000 ms (1 hour). Default is 0 (not a paid instance, no delay).

-   *threshold* - Nodes can be released if the current time is in interval [releaseDelay - threshold, releaseDelay]. Default is 0 (not a paid instance, no delay). Related to releaseDelay. Example for amazon : 600000 ms (10 minutes).

==== Cron Load Based Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.CronLoadBasedPolicy`

The *Cron load based policy* triggers new nodes acquisition when
scheduler is overloaded (exactly like with *"Scheduler loading" policy*)
only within a time slot defined using crontab syntax. All other time the
nodes are removed from the Resource Manager.
To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *schedulerURL* - URL of the Scheduler, e.g. pnp://mymachine:64738, pamr://0, etc

-   *schedulerCredentialsPath* - Path to the credentials used for
    scheduler authentication.

-   *schedulerAwarePolicyNodeSourceRecoveryDelay* - Delay in ms for the Resource Manager to recover a broken node source using the CronLoadBasedPolicy.

-   *schedulerAwarePolicyNodeSourceRecoveryTrialsNumber* - Number of attempts for the Resource Manager to recover to recover a broken node source using the CronLoadBasedPolicy.

-   *refreshTime* - Time between each calculation of the number of
    needed nodes.

-   *minNodes* - Minimum number of nodes to deploy

-   *maxNodes* - Maximum number of nodes to deploy

-   *loadFactor* - Number of tasks per node. Actually, if this number is
*N*, it does not means that there will be exactly *N* tasks executed on
each node. This factor is just used to compute the total number of
nodes. For instance, let us assume that this factor is 3 and that we
schedule 100 tasks. In that case, we will have 34 (= upper bound of
100/3) started nodes. Once one task finished and the refresh time
passed, one node will be removed since 99 divided by 3 is 33. When there
will remain 96 tasks (assuming that no other tasks are scheduled
meanwhile), an other node will be removed at the next calculation time,
and so on and so forth...

-   *refreshCycleWindow* - Number of refresh cycles used to memorize scheduler load. Actual load will be computed as an average.

-   *releaseDelay* - Delay in milliseconds used before removing a free node. This parameter can be used for paid cloud instances such as Amazon, Azure, etc. when their policy define a minimum granularity on instance costs. Example for Amazon : 3600000 ms (1 hour). Default is 0 (not a paid instance, no delay).

-   *threshold* - Nodes can be released if the current time is in interval [releaseDelay - threshold, releaseDelay]. Default is 0 (not a paid instance, no delay). Related to releaseDelay. Example for amazon : 600000 ms (10 minutes).

-   *acquisionAllowed* - The time when the policy starts to work as the
*"scheduler loading" policy* (e.g. "0 12 \* \* \*" every day at 12.00).

-   *acquisionForbidden* - The time policy removes all the nodes from the
Resource Manager (e.g. "0 13 \* \* \*" every day at 13.00).

-   *preemptive* - Preemptive parameter indicates the way of releasing
nodes. If it is true, nodes will be released without waiting the end of
jobs running on (default is false).

-   *allowed* - If true acquisition will be immediately allowed.

==== Cron Slot Load Based Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.CronSlotLoadBasedPolicy`

The *"Cron slot load based" policy* triggers new nodes acquisition when
scheduler is overloaded (exactly like with *"Scheduler loading" policy*)
only within a time slot defined using crontab syntax. The other time it
holds all the available nodes.
To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *schedulerURL* - URL of the Scheduler, e.g. pnp://mymachine:64738, pamr://0, etc

-   *schedulerCredentialsPath* - Path to the credentials used for
scheduler authentication.

-   *schedulerAwarePolicyNodeSourceRecoveryDelay* - Delay in ms for the Resource Manager to recover a broken node source using the CronSlotLoadBasedPolicy.

-   *schedulerAwarePolicyNodeSourceRecoveryTrialsNumber* - Number of attempts for the Resource Manager to recover to recover a broken node source using the CronSlotLoadBasedPolicy.

-   *refreshTime* - Time between each calculation of the number of needed
nodes.

-   *minNodes* - Minimum number of nodes to deploy

-   *maxNodes* - Maximum number of nodes to deploy

-   *loadFactor* - number of tasks per node. Actually, if this number is
*N*, it does not means that there will be exactly *N* tasks executed on
each node. This factor is just used to compute the total number of
nodes. For instance, let us assume that this factor is 3 and that we
schedule 100 tasks. In that case, we will have 34 (= upper bound of
100/3) started nodes. Once one task finished and the refresh time
passed, one node will be removed since 99 divided by 3 is 33. When there
will remain 96 tasks (assuming that no other tasks are scheduled
meanwhile), an other node will be removed at the next calculation time,
and so on and so forth...

-   *refreshCycleWindow* - Number of refresh cycles used to memorize scheduler load. Actual load will be computed as an average.

-   *releaseDelay* - Delay in milliseconds used before removing a free node. This parameter can be used for paid cloud instances such as Amazon, Azure, etc. when their policy define a minimum granularity on instance costs. Example for Amazon : 3600000 ms (1 hour). Default is 0 (not a paid instance, no delay).

-   *threshold* - Nodes can be released if the current time is in interval [releaseDelay - threshold, releaseDelay]. Default is 0 (not a paid instance, no delay). Related to releaseDelay. Example for amazon : 600000 ms (10 minutes).

-   *deployAllAt* - Time when all nodes are deployed (crontab format) (e.g. "0 12 \* \* \*" every day at 12.00).

-   *undeployAllAt* - Time when all nodes are removed and the policy starts watching the scheduler load (e.g. "0 13 \* \* \*" every day at 13.00).

-   *preemptive* - Preemptive parameter indicates the way of releasing
nodes. If it is true, nodes will be released without waiting the end of
tasks running on (default is false).

-   *acquireNow* - If true, the policy will acquire all nodes immediately.

==== Dynamic Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.DynamicPolicy`

The *Dynamic policy* is similar to the <<_scheduler_loading_policy>> in the sense that it can acquire/release nodes according to the
scheduler load. The *Dynamic policy* is more advanced and gives a fuller range of configuration parameters which allow to:
 - filter the scheduler load to specific tasks which use the `NODESOURCENAME` <<_glossary_generic_information,generic information>>.
 - delay the initial triggering of the policy.
 - release nodes after a configurable idle period.

This policy is very well suited to Cloud infrastructures (Azure, EC2, etc) when cloud instances need to be acquired on-demand.

Similarly to the <<_scheduler_loading_policy>>, it is important to correctly configure the maximum and minimum nodes that this
policy will try to hold in accordance with the underlying infrastructure.
This policy will never acquire more nodes than the infrastructure is capable of (as configured in the infrastructure parameters).
Symmetrically, if an infrastructure defines a minimum number of nodes to acquire, this policy will never go below this number.

To use this policy, you have to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *minNodes* - Minimum number of nodes to deploy

-   *maxNodes* - Maximum number of nodes to deploy

-   *schedulerUrl* - URL of the Scheduler, e.g. pnp://mymachine:64738, pamr://0, etc

-   *schedulerCredentialsPath* - Path to the credentials used for
scheduler authentication.

-   *schedulerConnectionTimeout* - Timeout in ms to establish connection with the scheduler.

-   *schedulerConnectionTrialsNumber* - Number of attempts to connect with the scheduler.

-   *refreshTime* - Time in milliseconds between each calculation of the number of
    needed nodes.

-   *loadFactor* - Number of tasks per node. Actually, if this number is
*N*, it does not means that there will be exactly *N* tasks executed on
each node. This factor is just used to compute the total number of
nodes. For instance, let us assume that this factor is 3 and that we
schedule 100 tasks. In that case, we will have 34 (= upper bound of
100/3) started nodes. Once one task finished and the refresh time
passed, one node will be removed since 99 divided by 3 is 33. When there
will remain 96 tasks (assuming that no other tasks are scheduled
meanwhile), another node will be removed at the next calculation time,
and so on ...
The load factor accepts decimal values to allow more precise control (1.5, etc.)

-   *initDelay* - Delay in milliseconds to initialize the infrastructure (eg. in a azure cloud infrastructure this must
cover the creation of Azure's initial resources such as network, storage account, etc.).

-   *minUptime* - Minimal uptime of a free node to be candidate for deletion (in milliseconds). For example, if this parameter
is set to 10 minutes, a node will not be removed from the node source unless it stays 10 minutes consecutively in state FREE, without executing any new task.

-   *globalScope* - if this parameter is set to `true`, the tasks considered to compute the load factor of the scheduler
will correspond to all pending tasks in the scheduler queue. If it is set to `false`, only tasks which contain the <<_glossary_generic_information,generic information>>
`NODESOURCENAME` with value equal to the node source name will be considered. This allows to restrict the provisioning of nodes to specific tasks.


===== Native Scheduler Policy

*Full name:* `org.ow2.proactive.resourcemanager.nodesource.policy.NativeSchedulerPolicy`

The Native Scheduler Policy interacts with the <<_glossary_ns_native_scheduler,native scheduler>> to request ProActive nodes deployment dynamically based on the <<_glossary_proactive_scheduler,*ProActive Scheduler*>> pending queue.
This mechanism is described in <<_deploy_via_other_schedulers>>. This policy must be associated with a <<_native_scheduler_infrastructure>> and cannot be associated with any other infrastructure.
To use this policy, you need to define the following parameters:

-   *userAccessType* - see <<_policy_common_parameters>>

-   *providerAccessType* - see <<_policy_common_parameters>>

-   *schedulerUrl* - URL of the Scheduler, e.g. pnp://mymachine:64738, pamr://0, etc

-   *schedulerCredentialsPath* - Path to a file which contains the credentials of an administrator user which will connect to the scheduler. The ProActive Scheduler Server release contains two admin users credentials files : `config/authentication/rm.cred` and `config/authentication/admin_user.cred`

-   *rearrangeTasks* - Currently not implemented.

-   *autoScaling* - If set to `true`, the NativeSchedulerPolicy will scan the Resource Manager activity and Scheduler queue. If the scheduler queue is not empty and all Resource Manager nodes are busy, `autoscaling` will automatically start ProActive Nodes from the NativeSchedulerInfrastructure. This setting cannot be used when multiple NativeScheduler node sources are deployed.

-   *refreshTime* -  The NativeSchedulerPolicy will refresh its status and observe the ProActive Scheduler queue every `refreshTime` milliseconds.

