An *Infrastructure Manager* is responsible for deploying nodes. In most of the cases it knows how to launch a node
on a remote machine. For instance the SSH infrastructure manager connects via SSH to a remote machine and launches
nodes.

===== Default Infrastructure Manager

*Default infrastructure manager* is designed to be used with ProActive
agent. It cannot perform an automatic deployment but any users
(including an agent) can add already existing nodes into it. In order to
create a node source with this infrastructure, run the following
command:

    $ PROACTIVE_HOME/bin/proactive-client --createns defaultns -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.DefaultInfrastructureManager rmURL

The only parameter to provide is the following one:

-   **rmURL** - the URL of the Resource Manager.

===== Local Infrastructure Manager

*Local Infrastructure Manager* can be used to start nodes locally, i.e,
on the host running the Resource Manager. In order to create a node
source with this infrastructure, run the following command:

    $ PROACTIVE_HOME/bin/proactive-client --createns localns -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.LocalInfrastructure rmURL credentialsPath numberOfNodes timeout javaProperties

-   *rmURL* - URL of the Resource Manager server (can leave it empty to
    use default value, i.e, the URL of the Resource Manager you connect
    to)

-   *credentialsPath* - The absolute path of the credentials file used
    to set the provider of the nodes.

-   *numberOfNodes* - The number of nodes to deploy.

-   *timeout* - The length in ms after which one a node is not expected
    anymore.

-   *javaProperties* - The java properties to setup the ProActive
    environment for the nodes

===== SSH Infrastructure

This infrastructure allows to deploy nodes over SSH.
This infrastructure needs 10 arguments, described hereafter:

-   **RM URL** - The Resource Manager's URL that will be used by the
    deployed nodes to register by themselves.

-   **SSH Options** - Options you can pass to the SSHClient executable (
    -l inria to specify the user for instance )

-   **Java Path** - Path to the java executable on the remote hosts.

-   **Scheduling Path** - Path to the Scheduler installation
    directory on the remote hosts.

-   **Node Time Out** - A duration after which one the remote nodes are
    considered to be lost.

-   **Attempt** - The number of time the Resource Manager tries to
    acquire a node for which one the deployment fails before discarding
    it forever.
    
    **Wait time between failed attempts** - The time in milliseconds that the Resource Manager wait before trying to
    acquire a node for which one the deployment fails before.

-   **Target OS** - One of 'LINUX', 'CYGWIN' or 'WINDOWS' depending on
    the machines' ( in Hosts List file ) operating system.

-   **Java Options** - Java options appended to the command used to
    start the node on the remote host.

-   **RM Credentials Path** - The absolute path of the 'rm.cred' file to
    make the deployed nodes able to register to the Resource Manager (
    config/authentication/rm.cred ).

-   **Hosts List** - Path to a file containing the hosts on which
    resources should be acquired. This file should contain one host per
    line, described as a host name or a public IP address, optionally
    followed by a positive integer describing the number of runtimes to
    start on the related host (default to 1 if not specified). Example:

        rm.example.com
        test.example.net 5
        192.168.9.10 2

===== CLI Infrastructure

This generic infrastructure allows to deploy nodes using deployment
script written in arbitrary language. The infrastructure just launches
this script and waits until the ProActive node is registered in the
Resource Manager. Command line infrastructure could be used when you
prefer to describe the deployment process using shell scripts instead of
Java. Script examples can be found in
+PROACTIVE_HOME/samples/scripts/deployment+. The deployment script has 4
parameters: +HOST_NAME+, +NODE_NAME+, +NODE_SOURCE_NAME+, +RM_URL+. The
removal script has 2 parameters: +HOST_NAME+ and +NODE_NAME+.

This infrastructure needs 7 arguments, described hereafter:

-   **RM URL** - The Resource Manager's URL that will be used by the
    deployed nodes to register by themselves.

-   **Interpreter** - Path to the script interpreter (bash by default).

-   **Deployment Script** - A script that launches a ProActive node and
    register it to the RM.

-   **Removal Script** - A script that removes the node from the
    Resource Manager.

-   **Hosts List** - Path to a file containing the hosts on which
    resources should be acquired. This file should contain one host per
    line, described as a host name or a public IP address, optionally
    followed by a positive integer describing the number of runtimes to
    start on the related host (default to 1 if not specified). Example:

        rm.example.com
        test.example.net 5
        192.168.9.10 2

-   **Node Time Out** - The length in ms after which one a node is not
    expected anymore.

-   **Max Deployment Failure** - the number of times the resource
    manager tries to relaunch the deployment script in case of failure.

===== EC2 Infrastructure

The Elastic Compute Cloud, aka *EC2*, is an Amazon Web Service, that
allows its users to use machines (instances) on demand on the cloud. An
EC2 instance is a Xen virtual machine, running on different kinds of
hardware, at different prices, but always paid by the hour, allowing
lots of flexibility. Being virtual machines, instances can be launched
using custom operating system images, called *AMI* (Amazon Machine
Image). For the Resource Manager to use EC2 instances as computing
nodes, a specific EC2 Infrastructure as well as AMI creation utilities
are provided.

To use the EC2 Infrastructure in the Resource Manager, proper Amazon
credentials are needed. This section describes briefly how to obtain
them, and how to use them to configure your environment.

1.  First, you need to create an AWS account at
    <http://aws.amazon.com/>.

2.  With your new AWS account, sign up for EC2 at
    <http://aws.amazon.com/ec2/>.

3.  Now, you need to obtain the credentials. http://aws.amazon.com[On the AWS website],
    point your browser to the _Your Web Services Account_ button, a drop
    down list displays. Click _View Access Key Identifiers_.

4.  Use this information to fill in the properties *aws_key* (Access
    Key), *aws_secret_key* (Secret Key) in the *Create Node Source* panel located in the Resource Manager.
    Those two parameters should never change, except if you need for
    some reason to handle multiple EC2 accounts. Other properties in the
    *Create Node Source* are:
    
    -   *rmHostname:* The hostname or the public IP address of the Resource Manager. This address needs to be accessible from the AWS cloud.
    
    -   *connectorIaasURL:* Connector-iaas is a service embedded in the Scheduler used to interact with IaaS like AWS. By default it runs on the following URL *rmHostname/connector-iaas*.

    -   *image:* Defines which AMI will be used to create an AWS instances. The
        value to provide is the AWS region together with the unique AMI Id, for example: `eu-west-1/ami-bff32ccc`.
        
    -   *numberOfInstances:* Total number of AWS instances to create for this infrastructure.
    
    -   *numberOfNodesPerInstance:* Total number of Proactive Nodes to deploy in each created AWS instance.
    
+
TIP: If all the nodes of an AWS instance are removed, the instance will be terminated. For more information on the terminated state in AWS please see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html[AWS Terminating Instances].
+       
    -   *downloadCommand:* The command to download the Proactive *node.jar*. This command is executed in all the newly created AWS instances.
    	The full URL path of the *node.jar* to download, needs to be accessible from the AWS cloud.
        Example based on AWS image with windows operating system:
        
        	powershell -command "& { (New-Object Net.WebClient).DownloadFile('try.activeeon.com/rest/node.jar', 'node.jar') }"
    	    	
    -   *additionalProperties:* Additional Java command properties to be added when starting each ProActive node JVM in the AWS instances (e.g. \"-Dpropertyname=propertyvalue\").
     
    -   *minRam:* The minimum required amount of RAM expressed in Mega Bytes for each AWS instance that needs to be created.
    
    -   *minCores:* The minimum required amount of virtual cores for each AWS instance that needs to be created.

+
WARNING: If the combination between RAM and CORES does not match any existing AWS instance type, then the closest to the specified parameters will be selected.

    -   *spotPrice:* The maximum price that you are willing to pay per hour per instance (your bid price). Amazon EC2 Spot instances allow you to bid on spare Amazon EC2 computing capacity. Since Spot instances are often available at a discount compared to On-Demand pricing. If your bid price is greater than the current Spot price for the specified instance, and the specified instance is available, your request is fulfilled immediately. Otherwise, the request is fulfilled whenever the Spot price falls below your bid price or the specified instance becomes available. Spot instances run until you terminate them or until Amazon EC2 must terminate them (also known as a Spot instance interruption). More information available on https://aws.amazon.com/ec2/spot/[AWS EC2 Spot]

    -   *securityGroupNames:* The securityGroupNames option allows you to specify the name(s) of the Security group(s) configured as a virtual firewall(s) to control inbound and outbound traffic for the EC2 instances hosting the proactive nodes. More information regarding Amazon EC2 Security Group available on http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-network-security.html[AWS EC2 Security Groups]

    -   *subnetId:* The subnetId option allows you to launch the proactive nodes on EC2 instances, which will run into an existing subnet added to a specific Virtual Private Cloud. More information regarding Amazon EC2 Virtual Private Cloud (Amazon VPC) available on https://aws.amazon.com/vpc/[AWS EC2 Virtual Private Cloud] and Amazon EC2 Virtual Private Cloud and Subnet available on http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html[AWS EC2 Virtual Private Cloud and Subnet]

+
Using this configuration, you can start a Resource Manager and a
Scheduler using the */bin/proactive-server* script. An EC2 NodeSource can
now be added using the *Create Node Source* panel in the Resource Manager or the command line interface:

    $ PROACTIVE_HOME/bin/proactive-client --createns ec2 -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.AWSEC2Infrastructure aws_key aws_secret_key rmDomain connectorIaasURL image numberOfInstances numberOfNodesPerInstance downloadCommand additionalProperties minRam minCores

As AWS is a paying service, when the Scheduler is stopped normally (without removing the created infrastructure), all the created AWS instances will be terminated. And when the Scheduler is restarted, these instances will be re-configured as per previous settings.

WARNING: If the Scheduler is forced killed, the created AWS instances will not be terminated. And, when the Scheduler is restarted, the infrastructure will be re-configured as per previous settings. If the instances were delete at the AWS side, they will be re-created and re-configured.



===== OpenStack Infrastructure

To use the OpenStack instances as computing nodes, a specific OpenStack Infrastructure
can be created using the Resource Manager. This section describes briefly how to make it.

1.  First, you need to have an admin account on your OpenStack server. For more information see
http://docs.openstack.org/icehouse/install-guide/install/yum/content/keystone-users.html[OpenStack users and tenants].

2.  Use the login, tenant and password information to fill in the properties *openstack_username* (`tenant:login`),
    *openstack_password* in the *Create Node Source* panel located in the Resource Manager.
    Those two parameters should never change, except if you need for some reason to handle multiple OpenStack accounts.
    Other properties in the *Create Node Source* are:
    
    -   *endpoint:* The hostname or the IP address of the OpenStack server. This address needs to be accessible from the Resource Manager.
    
    -   *rmHostname:* The hostname or the public IP address of the Resource Manager. This address needs to be accessible from the OpenStack server.
    
    -   *connectorIaasURL:* Connector-iaas is a service embedded in the Scheduler used to interact with IaaS like OpenStack. By default it runs on the following URL *rmHostname/connector-iaas*.

    -   *image:* Defines which image will be used to create the Openstack instance. The
        value to provide is the Openstack region together with the unique image Id, for example: `RegionOne/74oi56bff32ccc`.
        
    -   *flavor:* Defines the size of the instance. For more information see http://docs.openstack.org/openstack-ops/content/flavors.html[OpenStack flavors].
    
    -   *publicKeyName:* Defines the name of the public key to use for a remote connection when the instance is created.
    
+
WARNING: In order to use publicKeyName, the key pair needs to be created and imported first on the openstack server. For more information see https://community.hpcloud.com/article/managing-your-key-pairs-0[OpenStack key pair management].
+
 
        
    -   *numberOfInstances:* Total number of OpenStack instances to create for this infrastructure.
    
    -   *numberOfNodesPerInstance:* Total number of Proactive Nodes to deploy in each Openstack created instance.
    
+
TIP: If all the nodes of an Openstack instance are removed, the instance will be terminated.
+

       
    -   *downloadCommand:* The command to download the Proactive *node.jar*. This command is executed in all the newly created OpenStack instances.
    	The full URL path of the *node.jar* to download needs to be accessible from the OpenStack cloud.

    	    	
    -   *additionalProperties:* Additional Java command properties to be added when starting each ProActive node JVM in the OpenStack instances (e.g. \"-Dpropertyname=propertyvalue\").
    

Using this configuration, you can start a Resource Manager and a
Scheduler using the */bin/proactive-server* script. An OpenStack NodeSource can
now be added using the *Create Node Source* panel in the Resource Manager or the command line interface:

    $ PROACTIVE_HOME/bin/proactive-client --createns openstack -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.OpenstackInfrastructure username password endpoint rmHostname connectorIaasURL image flavor publicKeyName numberOfInstances numberOfNodesPerInstance downloadCommand additionalProperties


WARNING: When the Scheduler is stopped (without removing the created infrastructure), the OpenStack instances will not be terminated. And when the Scheduler is restarted, the infrastrucutre will be re-configured as per previous settings. If the instances were delete at the Openstack server side, they will be re-created and re-configured.



===== VmWare Infrastructure

To use the VmWare instances as computing nodes, a specific VmWare Infrastructure
can be created using the Resource Manager. This section describes briefly how to make it.

1.  First, you need to have an admin account on your VmWare server.For more information see
https://pubs.vmware.com/vsphere-51/topic/com.vmware.vsphere.security.doc/GUID-670B9B8C-3810-4790-AC83-57142A9FE16F.html[VmWare users].

2.  Use the login and password information to fill in the properties *vmware_username*,
    *vmware_password* in the *Create Node Source* panel located in the Resource Manager.
    Those two parameters should never change, except if you need for
    some reason to handle multiple VmWare accounts. Other properties in the
    *Create Node Source* are:
    
    -   *endpoint:* The hostname or the IP address of the VmWare server. This address needs to be accessible from the Resource Manager.
    
    -   *rmHostname:* The hostname or the public IP address of the Resource Manager. This address needs to be accessible from the VmWare server.
    
    -   *connectorIaasURL:* Connector-iaas is a service embedded in the Scheduler used to interact with IaaS like VmWare. By default it runs on the following URL *rmHostname/connector-iaas*.

    -   *image:* Defines which image will be used to create the VmWare instance. The
        value to provide is the VmWare folder together with the unique image Id, for example: `ActiveEon/ubuntu`.
        
    -   *minRam:* The minimum required amount of RAM expressed in Mega Bytes for each VmWare instance that needs to be created.
    
    -   *minCores:* The minimum required amount of virtual cores for each VmWare instance that needs to be created.
    
+
WARNING: If the combination between RAM and CORES does not match any existing VmWare instance type, then the closest to the specified parameters will be selected.
+

    -   *vmUsername:* Defines the username to log in the instance when it is created.
    
    -   *vmPassword:* Defines the password to log in the instance when it is created.
    
+
WARNING: The username and password are related to the image.
+
        
    -   *numberOfInstances:* Total number of VmWare instances to create for this infrastructure.
    
    -   *numberOfNodesPerInstance:* Total number of Proactive Nodes to deploy in each VmWare created instance.
    
+
TIP: If all the nodes of an VmWare instance are removed, the instance will be terminated.
+

       
    -   *downloadCommand:* The command to download the Proactive *node.jar*. This command is executed in all the newly created VmWare instances.
    	The full URL path of the *node.jar* to download, needs to be accessible from the VmWare cloud.
    	    	
    -   *additionalProperties:* Additional Java command properties to be added when starting each ProActive node JVM in the VmWare instances (e.g. \"-Dpropertyname=propertyvalue\").
    

Using this configuration, you can start a Resource Manager and a
Scheduler using the */bin/proactive-server* script. An VmWare NodeSource can
now be added using the *Create Node Source* panel in the Resource Manager or the command line interface:

    $ PROACTIVE_HOME/bin/proactive-client --createns vmware -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.VmwareInfrastructure username password endpoint rmHostname connectorIaasURL image ram cores vmusername vmpassword numberOfInstances numberOfNodesPerInstance downloadCommand additionalProperties


WARNING: When the Scheduler is stopped (without removing the created infrastructure), the VmWare instances will not be terminated. And when the Scheduler is restarted, the infrastrucutre will be re-configured as per previous settings. If the instances were delete at the VmWare server side, they will be re-created and re-configured.



===== Load Sharing Facility (LSF) infrastructure

This infrastructure knows how to acquire nodes from LSF by submitting a
corresponding job. It will be submitted through SSH from the RM to the
LSF server.

    $ PROACTIVE_HOME/bin/proactive-client --createns lsf -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.LSFInfrastructure rmURL javaPath SSHOptions schedulingPath javaOptions maxNodes nodeTimeout LSFServer RMCredentialsPath bsubOptions

where:

-   **RMURL** - URL of the Resource Manager from the LSF nodes point of
  view - this is the URL the nodes will try to lookup when attempting
  to register to the RM after their creation.

-   **javaPath** - path to the java executable on the remote hosts (ie
  the LSF slaves).

-   **SSH Options** - Options you can pass to the SSHClient executable (
  -l inria to specify the user for instance )

-   **schedulingPath** - path to the Scheduling/RM installation
  directory on the remote hosts.

-   **javaOptions** - Java options appended to the command used to start
  the node on the remote host.

-   **maxNodes** - maximum number of nodes this infrastructure can
  simultaneously hold from the LSF server. That is useful considering
  that LSF does not provide a mechanism to evaluate the number of
  currently available or idle cores on the cluster. This can result to
  asking more resources than physically available, and waiting for the
  resources to come up for a very long time as the request would be
  queued until satisfiable.

-   **Node Time Out** - The length in ms after which one a node is not
  expected anymore.

-   **Server Name** - URL of the LSF server, which is responsible for
  acquiring LSF nodes. This server will be contacted by the Resource
  Manager through an SSH connection.

-   **RM Credentials Path** - Encrypted credentials file, as created by
  the create-cred[.bat] utility. These credentials will be used by the
  nodes to authenticate on the Resource Manager.

-   **Submit Job Opt** - Options for the bsub command client when
  acquiring nodes on the LSF master. Default value should be enough in
  most cases, if not, refer to the documentation of the LSF cluster.

===== Portable Batch System (PBS) infrastructure

This infrastructure knows how to acquire nodes from PBS (i.e. Torque) by
submitting a corresponding job. It will be submitted through SSH from
the RM to the PBS server.

    $ PROACTIVE_HOME/bin/proactive-client --createns pbs -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.PBSInfrastructure rmURL javaPath SSHOptions schedulingPath javaOptions maxNodes nodeTimeout PBSServer RMCredentialsPath qsubOptions

where:

-   **RMURL** - URL of the Resource Manager from the PBS nodes point of
    view - this is the URL the nodes will try to lookup when attempting
    to register to the RM after their creation.

-   **javaPath** - path to the java executable on the remote hosts (ie
    the PBS slaves).

-   **SSH Options** - Options you can pass to the SSHClient executable (
    -l inria to specify the user for instance )

-   **schedulingPath** - path to the Scheduling/RM installation
    directory on the remote hosts.

-   **javaOptions** - Java options appended to the command used to start
    the node on the remote host.

-   **maxNodes** - maximum number of nodes this infrastructure can
    simultaneously hold from the PBS server. That is useful considering
    that PBS does not provide a mechanism to evaluate the number of
    currently available or idle cores on the cluster. This can result to
    asking more resources than physically available, and waiting for the
    resources to come up for a very long time as the request would be
    queued until satisfiable.

-   **Node Time Out** - The length in ms after which one a node is not
    expected anymore.

-   **Server Name** - URL of the PBS server, which is responsible for
    acquiring PBS nodes. This server will be contacted by the Resource
    Manager through an SSH connection.

-   **RM Credentials Path** - Encrypted credentials file, as created by
    the create-cred[.bat] utility. These credentials will be used by the
    nodes to authenticate on the Resource Manager.

-   **Submit Job Opt** - Options for the qsub command client when
    acquiring nodes on the PBS master. Default value should be enough in
    most cases, if not, refer to the documentation of the PBS cluster.


===== Generic Batch Job infrastructure

*Generic Batch Job infrastructure* provides users with the capability to
add the support of new batch job scheduler by providing a class
extending
org.ow2.proactive.resourcemanager.nodesource.infrastructure.BatchJobInfrastructure.
Once you have written that implementation, you can create a node source
which makes usage of this infrastructure by running the following
command:

    $ PROACTIVE_HOME/bin/proactive-client --createns pbs -infrastructure org.ow2.proactive.resourcemanager.nodesource.infrastructure.GenericBatchJobInfrastructure rmURL javaPath SSHOptions schedulingPath javaOptions maxNodes nodeTimeout BatchJobServer RMCredentialsPath subOptions implementationName implementationPath

where:

-   **RMURL** - URL of the Resource Manager from the batch job scheduler
    nodes point of view - this is the URL the nodes will try to lookup
    when attempting to register to the RM after their creation.

-   **javaPath** - path to the java executable on the remote hosts (ie
    the slaves of the batch job scheduler).

-   **SSH Options** - Options you can pass to the SSHClient executable (
    -l inria to specify the user for instance )

-   **schedulingPath** - path to the Scheduling/RM installation
    directory on the remote hosts.

-   **javaOptions** - Java options appended to the command used to start
    the node on the remote host.

-   **maxNodes** - maximum number of nodes this infrastructure can
    simultaneously hold from the batch job scheduler server.

-   **Node Time Out** - The length in ms after which one a node is not
    expected anymore.

-   **Server Name** - URL of the batch job scheduler server, which is
    responsible for acquiring nodes. This server will be contacted by
    the Resource Manager through an SSH connection.

-   **RM Credentials Path** - Encrypted credentials file, as created by
    the create-cred[.bat] utility. These credentials will be used by the
    nodes to authenticate on the Resource Manager.

-   **Submit Job Opt** - Options for the submit command client when
    acquiring nodes on the batch job scheduler master.

-   **implementationName** - Fully qualified name of the implementation
    of
    org.ow2.proactive.resourcemanager.nodesource.infrastructure.BatchJobInfrastructure
    provided by the end user.

-   **implementationPath** - The absolute path of the implementation of
    org.ow2.proactive.resourcemanager.nodesource.infrastructure.BatchJobInfrastructure.

