= Tutorials: ProActive Workflows & Scheduling
include::../common-settings.adoc[]
:toc-title: Tutorials for Administrators

== Step by Step Tutorials

=== Run As Me
This is a step by step tutorial, which was designed and tested for Ubuntu 14.04.

ProActive Workflows & Scheduling allows advanced user management with the “run as me” feature. Run as me allows
to execute a task under the current ProActive user, if an equally named system user exists on the executing machine.

*Following steps configure the Node with a sample user called Gord:*

. Create a group called proactive `groupadd proactive’
. Create a user running the ProActive Node, set it's primary group to proactive
 ‘useradd -g proactive -G sudo -m proactive’
. Set the password of proactive user ‘passwd proactive’
. Download and unzip ProActive inside the /opt/ directory (/opt/ gives execution right to everyone)
. Change ownership of the ProActive folder with ‘sudo chown -R proactive:proactive ProActiveNode’
. Add a run as me user, which is part of the proactive group ‘useradd -g proactive -m Gord’
. Create an ssh key for the run as me user (Gord) ‘ssh-keygen -t rsa’
. Go into the /home/Gord/.ssh directory and copy Gord’s public key to the authorized keys ‘cat id_rsa.pub >> authorized_keys’
. Log into the proactive account
. Start the ProActive Node with the property ‘-Dpas.launcher.forkas.method=key’

NOTE: The proactive user got a password set with 'passwd proactive' to execute the sudo command. Whereas
the run as me user (Gord) got a SSH key set. If you wish you can assign a password to Gord 'passwd Gord'.

*Following steps configure the Scheduler with a sample user called Gord:*

. Add Gord:Gord (Username:Password) to PROACTIVE_HOME/config/authentication/login.cfg
. Add Gord to the admin group by adding Gord:admin (Username:Group) to the PROACTIVE_HOME/config/authentication/group.cfg
. Start the Scheduler
. Log in as Gord
. Add the private key of Gord in the Scheduler interface under "Manage third-party credentials". Key: SSH_PRIVATE_KEY,
Credential: [Content of Gords' private key, with '-----BEGIN RSA PRIVATE KEY-----' and '-----END RSA PRIVATE KEY-----'
. Create a task in the Studio and tick "Run as me"

NOTE: The ProActive Node must be installed in a directory where every parent directory gives execution rights to users, which
execute tasks.
The users need to be part of the proactive group because a task needs the rights to write logs. Which is achieved by
being part of the proactive group and the proactive group ownership of the ProActive Node directory.
